
import React from 'react';
import { Repository, PortfolioItem } from '../types';
import { X, Download, FileText, FileJson2, Table2, Star, Zap } from './Icons';

interface ExportModalProps {
  repos: Repository[];
  portfolio: PortfolioItem[];
  summary: string;
  topic: string;
  onClose: () => void;
}

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function reposToMarkdown(repos: Repository[], title: string, summary?: string): string {
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  let md = `# ${title}\n\n`;
  md += `> Generated by GitTrend AI on ${date}\n\n`;

  if (summary) {
    md += `## Market Summary\n\n${summary}\n\n---\n\n`;
  }

  md += `## Repositories (${repos.length})\n\n`;
  repos.forEach((r, i) => {
    md += `### ${i + 1}. ${r.name}\n\n`;
    md += `| Field | Value |\n|---|---|\n`;
    md += `| Owner | ${r.owner} |\n`;
    md += `| Stars | ${r.stars} |\n`;
    md += `| Language | ${r.language} |\n`;
    md += `| Trending Score | ${r.trendingScore}/100 |\n`;
    if (r.sentimentScore !== undefined) md += `| Sentiment Score | ${r.sentimentScore}/100 |\n`;
    md += `| URL | [${r.url}](${r.url}) |\n`;
    if (r.tags?.length) md += `| Tags | ${r.tags.join(', ')} |\n`;
    md += `\n${r.description}\n\n`;
  });

  return md;
}

function reposToCSV(repos: Repository[]): string {
  const headers = ['Name', 'Owner', 'Description', 'Language', 'Stars', 'Trending Score', 'Sentiment Score', 'Tags', 'URL'];
  const escape = (v: string) => `"${(v || '').replace(/"/g, '""')}"`;
  const rows = repos.map(r => [
    escape(r.name),
    escape(r.owner),
    escape(r.description),
    escape(r.language),
    escape(r.stars),
    String(r.trendingScore || 0),
    String(r.sentimentScore || ''),
    escape((r.tags || []).join('; ')),
    escape(r.url),
  ]);
  return [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
}

function reposToJSON(repos: Repository[], meta?: { topic?: string; summary?: string }): string {
  return JSON.stringify({ meta: { ...meta, exportedAt: new Date().toISOString(), count: repos.length }, repositories: repos }, null, 2);
}

interface ExportSectionProps {
  title: string;
  subtitle: string;
  count: number;
  onMarkdown: () => void;
  onJSON: () => void;
  onCSV: () => void;
  disabled?: boolean;
}

const ExportSection: React.FC<ExportSectionProps> = ({ title, subtitle, count, onMarkdown, onJSON, onCSV, disabled }) => (
  <div className={`p-6 bg-gray-900/50 rounded-2xl border border-gray-800 ${disabled ? 'opacity-40 pointer-events-none' : ''}`}>
    <div className="flex items-center justify-between mb-4">
      <div>
        <h3 className="text-white font-bold text-sm">{title}</h3>
        <p className="text-[10px] text-gray-500">{subtitle}</p>
      </div>
      <span className="px-2 py-1 bg-cyan-900/30 text-cyan-400 text-[10px] font-bold rounded-full">
        {count} items
      </span>
    </div>

    <div className="grid grid-cols-3 gap-3">
      <button
        onClick={onMarkdown}
        className="group flex flex-col items-center p-4 bg-gray-800/50 hover:bg-gray-800 border border-gray-700/50 hover:border-cyan-500/30 rounded-xl transition-all"
      >
        <FileText size={20} className="text-cyan-400 mb-2 group-hover:scale-110 transition-transform" />
        <span className="text-xs font-bold text-white">Markdown</span>
        <span className="text-[9px] text-gray-500">.md</span>
      </button>

      <button
        onClick={onJSON}
        className="group flex flex-col items-center p-4 bg-gray-800/50 hover:bg-gray-800 border border-gray-700/50 hover:border-emerald-500/30 rounded-xl transition-all"
      >
        <FileJson2 size={20} className="text-emerald-400 mb-2 group-hover:scale-110 transition-transform" />
        <span className="text-xs font-bold text-white">JSON</span>
        <span className="text-[9px] text-gray-500">.json</span>
      </button>

      <button
        onClick={onCSV}
        className="group flex flex-col items-center p-4 bg-gray-800/50 hover:bg-gray-800 border border-gray-700/50 hover:border-amber-500/30 rounded-xl transition-all"
      >
        <Table2 size={20} className="text-amber-400 mb-2 group-hover:scale-110 transition-transform" />
        <span className="text-xs font-bold text-white">CSV</span>
        <span className="text-[9px] text-gray-500">.csv</span>
      </button>
    </div>
  </div>
);

const ExportModal: React.FC<ExportModalProps> = ({ repos, portfolio, summary, topic, onClose }) => {
  const slug = topic.toLowerCase().replace(/\s+/g, '-');
  const date = new Date().toISOString().split('T')[0];

  const handleTrendsMD = () => {
    downloadFile(
      reposToMarkdown(repos, `${topic} - Trends Intelligence Report`, summary),
      `gittrend-${slug}-trends-${date}.md`,
      'text/markdown'
    );
  };

  const handleTrendsJSON = () => {
    downloadFile(
      reposToJSON(repos, { topic, summary }),
      `gittrend-${slug}-trends-${date}.json`,
      'application/json'
    );
  };

  const handleTrendsCSV = () => {
    downloadFile(reposToCSV(repos), `gittrend-${slug}-trends-${date}.csv`, 'text/csv');
  };

  const handlePortfolioMD = () => {
    downloadFile(
      reposToMarkdown(portfolio, `${topic} - My Portfolio`),
      `gittrend-portfolio-${date}.md`,
      'text/markdown'
    );
  };

  const handlePortfolioJSON = () => {
    downloadFile(
      reposToJSON(portfolio, { topic }),
      `gittrend-portfolio-${date}.json`,
      'application/json'
    );
  };

  const handlePortfolioCSV = () => {
    downloadFile(reposToCSV(portfolio), `gittrend-portfolio-${date}.csv`, 'text/csv');
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/95 backdrop-blur-sm" onClick={onClose}></div>
      <div className="relative bg-[#0a0f18] border border-gray-800 rounded-2xl w-full max-w-2xl shadow-2xl animate-fade-in">
        {/* Header */}
        <div className="p-8 border-b border-gray-800 flex justify-between items-start">
          <div className="flex items-center space-x-4">
            <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-cyan-600 to-blue-700 flex items-center justify-center shadow-lg">
              <Download size={24} className="text-white" />
            </div>
            <div>
              <h2 className="text-2xl font-black text-white tracking-tight">Export Hub</h2>
              <p className="text-sm text-gray-500">Download your intelligence data in multiple formats</p>
            </div>
          </div>
          <button onClick={onClose} className="p-2 text-gray-400 hover:text-white transition-colors">
            <X size={24} />
          </button>
        </div>

        {/* Content */}
        <div className="p-8 space-y-6">
          <ExportSection
            title="Trends Intelligence"
            subtitle={`Current search results for "${topic}"`}
            count={repos.length}
            onMarkdown={handleTrendsMD}
            onJSON={handleTrendsJSON}
            onCSV={handleTrendsCSV}
            disabled={repos.length === 0}
          />

          <ExportSection
            title="My Portfolio"
            subtitle="Your curated repository collection"
            count={portfolio.length}
            onMarkdown={handlePortfolioMD}
            onJSON={handlePortfolioJSON}
            onCSV={handlePortfolioCSV}
            disabled={portfolio.length === 0}
          />
        </div>

        {/* Footer */}
        <div className="px-8 py-4 border-t border-gray-800 flex items-center justify-between">
          <p className="text-[9px] text-gray-600 font-bold uppercase tracking-widest">
            GitTrend AI Export Pipeline
          </p>
          <div className="flex items-center space-x-2 text-[10px] text-gray-600">
            <Star size={10} />
            <span>{repos.length + portfolio.length} total exportable items</span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ExportModal;
